### 회원가입(manager)
POST http://localhost:8080/signup/manager
Content-Type: application/json

{
  "birth": "1997-02-11",
  "email": "kys1064@naver.com",
  "name": "YS",
  "password": "pw",
  "phone": "01000000000"
}

### 이메일 인증(manager)
GET http://localhost:8080/signup/manager/verify/?email=kys1064@naver.com&code=yFWiWaTdsp

### 로그인(manager)
POST http://localhost:8080/signIn/manager
Content-Type: application/json

{
  "email": "kys1064@naver.com",
  "password": "pw"
}

### 스토어 생성(manager)
POST http://localhost:8080/store/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiTUFOQUdFUiIsImlhdCI6MTY4MTc3NjE1NSwiZXhwIjoxNjgxODYyNTU1fQ.z6D2RbLn9EZ-eHun7aghUdUXqCBsOHFXUgCr2dKpElM

{
  "managerId": 1,
  "store_name": "test 가게",
  "store_phone": "02-1234-5678",
  "address": "Test 주소"
}

### 가게 정보 수정(manager)
PUT http://localhost:8080/store/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiTUFOQUdFUiIsImlhdCI6MTY4MTc3NjE1NSwiZXhwIjoxNjgxODYyNTU1fQ.z6D2RbLn9EZ-eHun7aghUdUXqCBsOHFXUgCr2dKpElM

{
  "store_name": "수정 가게",
  "store_phone": "02-9876-5432",
  "address": "수정 주소"
}

### 가게 삭제(manager)
DELETE http://localhost:8080/store/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiTUFOQUdFUiIsImlhdCI6MTY4MTM3Mjc4NSwiZXhwIjoxNjgxNDU5MTg1fQ.I2BX8Xupdw8vDc0Yt-BU13m7GbzAbY4rpbRbqEmLMt0

### 가게 검색(manager)
GET http://localhost:8080/store/search?searchKeyword=가게&page=0&size=10&sort=storeName,asc
Content-Type: application/json

### 가게 정보 조회(manager)
GET http://localhost:8080/store/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiTUFOQUdFUiIsImlhdCI6MTY4MTM3Mjc4NSwiZXhwIjoxNjgxNDU5MTg1fQ.I2BX8Xupdw8vDc0Yt-BU13m7GbzAbY4rpbRbqEmLMt0

### 회원가입(customer)
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
"birth": "1997-02-11",
"email": "kys1064@naver.com",
"name": "YS",
"password": "pw",
"phone": "01000000000"
}

### 이메일 인증(customer)
GET http://localhost:8081/signup/customer/verify/?email=kys1064@naver.com&code=vXrKdcvtm2

### 로그인(customer)
POST http://localhost:8081/signIn/customer
Content-Type: application/json

{
  "email": "kys1064@naver.com",
  "password": "pw"
}

### 예약생성(customer)
POST http://localhost:8081/customer/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE3NzYyMTIsImV4cCI6MTY4MTg2MjYxMn0.aanWhRebdWraz7yHFhYPQRTiNWGYMxfvvr6dgTEfLbo

{
  "store_id": 1,
  "customer_phone": "010-1234-5678",
  "reservation_time": "2023-04-14T19:30:00",
  "reservation_status": "예약됨"
}

### 예약 상세 정보 조회(customer)
GET http://localhost:8081/customer/reservations/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE3NzYyMTIsImV4cCI6MTY4MTg2MjYxMn0.aanWhRebdWraz7yHFhYPQRTiNWGYMxfvvr6dgTEfLbo

### 예약 수정(customer)
PUT http://localhost:8081/customer/reservations/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE3NzYyMTIsImV4cCI6MTY4MTg2MjYxMn0.aanWhRebdWraz7yHFhYPQRTiNWGYMxfvvr6dgTEfLbo

{
  "store_id": 1,
  "customer_phone": "010-4321-8765",
  "reservation_time": "2023-04-20T19:30:00",
  "reservation_status": "예약 변경됨"
}

### 예약 취소(customer)
DELETE http://localhost:8081/customer/reservations/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE3NzYyMTIsImV4cCI6MTY4MTg2MjYxMn0.aanWhRebdWraz7yHFhYPQRTiNWGYMxfvvr6dgTEfLbo

### 예약 체크인(customer)
POST http://localhost:8081/customer/reservations/1/check-in
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE3NzYyMTIsImV4cCI6MTY4MTg2MjYxMn0.aanWhRebdWraz7yHFhYPQRTiNWGYMxfvvr6dgTEfLbo

### 예약 취소 - 체크인 10분 안함(customer)
DELETE http://localhost:8081/customer/reservations/2/cancel-no-check-in
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE2OTk4MDUsImV4cCI6MTY4MTc4NjIwNX0.u0fpS_mOpd00I_nOeCaFa5QUv0-ThmUjRcghJGm8qIQ

### 리뷰 생성(customer)
POST http://localhost:8081/customer/reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE2OTk4MDUsImV4cCI6MTY4MTc4NjIwNX0.u0fpS_mOpd00I_nOeCaFa5QUv0-ThmUjRcghJGm8qIQ

{
  "reservation_id": 1,
  "comment": "맛집!",
  "rating": 5
}

### 리뷰 상세 조회(customer)
GET http://localhost:8081/customer/reviews/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE2OTk4MDUsImV4cCI6MTY4MTc4NjIwNX0.u0fpS_mOpd00I_nOeCaFa5QUv0-ThmUjRcghJGm8qIQ

### 리뷰 수정(customer)
PUT http://localhost:8081/customer/reviews/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE2OTk4MDUsImV4cCI6MTY4MTc4NjIwNX0.u0fpS_mOpd00I_nOeCaFa5QUv0-ThmUjRcghJGm8qIQ

{
  "comment": "좋아요!",
  "rating": 3
}

### 리뷰 삭제(customer)
DELETE http://localhost:8081/customer/reviews/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE2OTk4MDUsImV4cCI6MTY4MTc4NjIwNX0.u0fpS_mOpd00I_nOeCaFa5QUv0-ThmUjRcghJGm8qIQ

### 특정 매장 리뷰 목록 조회(customer)
GET http://localhost:8081/customer/reviews/store/2?page=0&size=10&sort=rating,desc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyTTNMWDM3TTB2Uy82VXRTYlY2ZzZCWHM5czVwdFM2aGRWYm1nVjlLbStjPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiQ1VTVE9NRVIiLCJpYXQiOjE2ODE2OTk4MDUsImV4cCI6MTY4MTc4NjIwNX0.u0fpS_mOpd00I_nOeCaFa5QUv0-ThmUjRcghJGm8qIQ