### manager 회원가입
POST http://localhost:8080/signup/manager
Content-Type: application/json

{
  "birth": "1997-02-11",
  "email": "kys1064@naver.com",
  "name": "YS",
  "password": "pw",
  "phone": "01000000000"
}

### customer 회원가입
POST http://localhost:8081/signup/customer
Content-Type: application/json

{
"birth": "1997-02-11",
"email": "kys1064@naver.com",
"name": "YS",
"password": "pw",
"phone": "01000000000"
}